# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    database: multipledatabase_development
    username: postgres
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } + 5 %>
  queues_primary:
    database: queue_development
    username: postgres
    adapter: postgresql
    migrations_paths: db/queues_migrate
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } + 5 %>

test:
  primary:
    database: multipledatabase_test
    username: postgres
    adapter: postgresql
  queues_primary:
    database: queues_test
    username: postgres
    password: <%= ENV['ANIMALS_ROOT_PASSWORD'] %>
    adapter: postgresql
    migrations_paths: db/queues_migrate

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary:
    database: multipledatabase_production
    username: multipledatabase
    password: <%= ENV["MULTIPLEDATABASE_DATABASE_PASSWORD"] %>
  queues_primary:
    database: queues_production
    username: postgres
    password: <%= ENV['ANIMALS_ROOT_PASSWORD'] %>
    adapter: postgresql
    migrations_paths: db/queues_migrate
