name: Rails Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db1:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "123456"
          POSTGRES_DB: primary
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      db2:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "123456"
          POSTGRES_DB: good_job_queues
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Build and create DB
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPORT: 5432
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bin/rails db:setup

      - name: Run tests
        env:
          DATABASE_URL1: postgres://postgres:@localhost:5432/primary
          DATABASE_URL2: postgres://postgres:@localhost:5433/good_job_queues
        run: bundle exec rspec
